---
name: wedback
on:
  - push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedback
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./wedback/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: ./wedback
          version: latest
          args: --enable-all --timeout=30m

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedback
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./wedback/go.mod"
      - run: go test -v ./...
