---
name: wedfront
on:
  push:
    paths:
      - "wedfront/**"
      - ".github/workflows/wedfront.yaml"
  pull_request:
    paths:
      - "wedfront/**"
      - ".github/workflows/wedfront.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedfront
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: ./wedfront/package.json
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./wedfront/package.json
          cache: "pnpm"
          cache-dependency-path: ./wedfront/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedfront
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: ./wedfront/package.json
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./wedfront/package.json
          cache: "pnpm"
          cache-dependency-path: ./wedfront/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
