---
name: wedfront
on:
  push:
    paths:
      - "wedfront/**"
      - ".github/workflows/wedfront.yaml"
  pull_request:
    paths:
      - "wedfront/**"
      - ".github/workflows/wedfront.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedfront
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "./wedfront/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format
      - run: '[[ -z $(git status -s) ]]'

  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedfront
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "./wedfront/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
